# Generated by Django 3.2.6 on 2021-09-14 14:13

from django.db import migrations, models
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Active')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('terminal_type', models.CharField(choices=[('python', 'Python'), ('javascript', 'Javascript'), ('bash', 'Bash'), ('shell', 'Shell'), ('cmd', 'CMD')], default='bash', max_length=32)),
            ],
            options={
                'default_permissions': [],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
